project:
  type: website
  output-dir: docs
#  resources:
#    - images/**
#resource-path:
#  - images
#  - .

website:
  title: "KlimaResilienzSchule"
  site-url: https://OGERHub.github.io/KlimaResilienzSchule
  repo-url: https://github.com/OGERHub/KlimaResilienzSchule
  repo-actions: []   # [source, issue, edit] bei Bedarf manuell setzen
  page-navigation: true
  bread-crumbs: false
  open-graph: true
  twitter-card: true
  image: images/polaroidheader-og.jpg
  page-footer:
    center: |
      Geographiedidaktik - Schwerpunkt Physische Geographie (<span class="year"></span>) —
      <a class="impressum-link" href="../Über/impressum.html">Impressum</a>

  search:
    location: navbar
    type: textbox

  navbar:
    background: primary
    foreground: light
    logo: images/your-logo.png
    right:
      - icon: chat-left-text-fill
        text: "Ilias"
        href: "https://www.ilias.uni-koeln.de/ilias/login.php?client_id=uk&cmd=force_login&lang=de"

  sidebar:
    pinned: true
    align: center
    style: docked
    contents: auto
    collapse-level: 1
    # contents:
    #   - section: "Willkommen"
    #     contents:
    #       - index.qmd
    #       - base/about.qmd
    #   - text: "---"
    #   - section: "Kurs-Sitzungen"
    #     contents:
    #       - section: "Sitzung 1"
    #         contents:
    #           - session-1/sitzung-1-01.qmd
    #       - section: "Sitzung 2"
    #         contents:
    #           - session-2/sitzung-2-01.qmd
    #           - session-2/sitzung-2-02.qmd

format:
  html:
    theme:
      light: [lumen]
    css: css/styles.css
    toc: true
    code-copy: true
    code-background: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)//(OGERHub\.github\.io/KlimaResilienzSchule|github\.com/OGERHub/KlimaResilienzSchule)'
    md-extensions: +fenced_divs+bracketed_spans+link_attributes
    include-after-body:
      - "includes/_footer-year.html"


lang: de
